services:
  db:
    image: "postgres:9.6-alpine"
    container_name: db
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
    ports:
      - 5432:5432
  gitea:
    image: gitea/gitea:1.22.2-rootless
    container_name: gitea
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./data:/var/lib/gitea
    ports:
      - 3000:3000
volumes:
  dbdata: 
