services:
  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD:kanban
      - POSTGRES_DB:kanban
      - POSTGRES_USER:kanban
    volumes: 
      - C:\data\mysql-e:/var/lib/postgresql/data
  kanban-app:
    build: ./kanban-app
    container_name: kanban-app
    environment:
      - DB_SERVER=kanban-postgres
    ports:
      - 8080:8080
    links:
      - kanban-postgres
    depends_on:
      - kanban-postgres # Attend que la db soit prête pour commencer
  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    ports:
      - 4200:80
    links:
      - kanban-app
volumes:
  dbdata: 
