services:
  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    ports:
      - 5432:5432
 
  kanban-app:
    build: ./kanban-app
    environment:
      DB_SERVER: kanban-postgres
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    ports:
      - 8080:80
    links:
      - kanban-postgres
 
  kanban-ui:
    build: ./kanban-ui
    ports:
      - 4200:80
    links:
      - kanban-app
volumes:
  dbdata: 
